name: your_app_name
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Packages
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons_bottom_navigation_bar/
    - assets/developers/
    - assets/top10/
    - assets/icons_clips/
